name: minimal_rest
description: MinRest acts as a REST Client and Service/Datasource and returns data as your `DataModel` or `Entity` whichever object you want.
repository: https://github.com/niamulhasan/min_rest
version: 1.0.0
homepage: https://www.niamulhasan.me


environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  http: ^0.13.5
  dartz: ^0.10.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
